# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68464120d487ad0eea738d6d9f7ea7b5697b7ee6e94613eb36b8a6afb8adf89eec959fbe8714634fbb85ec0ec710bfe9e8b25f8609316fd16c241a5cd1c140ca

test:
  secret_key_base: 5196b7482eb4ca656f310717f0967ba418509ce41b2a47bb53f573fde82638e75518d38d1824faf2a3a70b45ed8fe9e72fb2c4c3b917fd53f51e815bd39a4a14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
